ARCHITECTURE=riscv64
QEMU_MACHINE=microchip-icicle-kit
RELEASE_ASSET_PREFIX=riscv64-microchip-icicle-kit
DEFAULT_BOOT_MODE=firmware
SUPPORTED_BOOT_MODES=(firmware)
REQUIRED_IMAGES=(hss.bin sdcard.img)
POWER_OF_TWO_IMAGES=(sdcard.img)
SDCARD_IMG_SIZE=$((4 * 1024 * 1024 * 1024))
GPT_IMAGES=(sdcard.img)
