ARCHITECTURE=riscv64
QEMU_MACHINE=microchip-icicle-kit
RELEASE_ASSET_PREFIX=riscv64-microchip-icicle-kit
DEFAULT_BOOT_MODE=firmware
SUPPORTED_BOOT_MODES=(firmware)
REQUIRED_IMAGES=(hss.bin sdcard.img)
