ARCHITECTURE=arm
QEMU_MACHINE=mcimx6ul-evk
RELEASE_ASSET_PREFIX=arm-mcimx6ul-evk
DEFAULT_BOOT_MODE=firmware
SUPPORTED_BOOT_MODES=(firmware linux)
FIRMWARE_IMAGES=(u-boot.bin sdcard.img)
LINUX_IMAGES=(zImage imx6ul-14x14-evk.dtb sdcard.img)
REQUIRED_IMAGES=(u-boot.bin zImage imx6ul-14x14-evk.dtb sdcard.img)
POWER_OF_TWO_IMAGES=(sdcard.img)
